"""One short example per built-in, for the components reference.

Each is a fragment of a page: the guide's tests parse it inside one, so an
example that stops compiling fails the build of the docs. Keep them short —
the chapters show the elements at length.
"""

EXAMPLES = {
    "Container": 'Container { Heading("Pricing").h1 }\nContainer.fluid { Text("Edge to edge") }',
    "Row": 'Row(gap: .md, align: .center, justify: .between) {\n    Text("Left")\n    Button("Right")\n}\nRow(direction: { base: .column, md: .row }) { Text("a")  Text("b") }',
    "Column": 'Row {\n    Column(span: 8) { Text("Main") }\n    Column(span: 4) { Text("Aside") }\n}',
    "Grid": 'Grid(columns: { base: 1, md: 3 }, gap: .lg) {\n    Card { Text("One") }\n    Card { Text("Two") }\n    Card { Text("Three") }\n}',
    "Stack": 'Stack(gap: .sm) {\n    Text("First")\n    Text("Second")\n}',
    "Spacer": 'Text("Above")\nSpacer.lg\nText("Below")',
    "Divider": 'Text("Section one")\nDivider\nText("Section two")',
    "Host": 'Host(tag: "canvas", mount: (node) => node.getContext("2d"), cleanup: (ctx) => log("gone"))',
    "Navbar": 'Navbar {\n    Navbar.Brand { Link("Acme", to: "/") }\n    Navbar.Links { Link("Docs", to: "/docs")  Link("Pricing", to: "/pricing") }\n    Navbar.Actions { Button("Sign in").sm }\n}',
    "Sidebar": 'Sidebar {\n    Sidebar.Header { Text("Console").bold }\n    Sidebar.Item(to: "/", icon: "home") { Text("Overview") }\n    Sidebar.Divider\n    Sidebar.Item(to: "/settings", icon: "settings") { Text("Settings") }\n}',
    "Link": 'Link("About us", to: "/about")\nLink("Guide", to: "/docs", active: .prefix)\nLink(to: "https://example.com", target: "_blank") { Text("Example") }',
    "Tabs": 'Tabs {\n    Tabs.Page("Profile") { Text("Your details") }\n    Tabs.Page("Billing") { Text("Your plan") }\n}',
    "Breadcrumb": 'Breadcrumb {\n    Breadcrumb.Item(to: "/") { Text("Home") }\n    Breadcrumb.Item(to: "/docs") { Text("Docs") }\n    Breadcrumb.Item { Text("Components") }\n}',
    "Menu": 'Menu(trigger: "Options") {\n    Menu.Item { Text("Rename") }\n    Menu.Divider\n    Menu.Item { Text("Delete") }\n}',
    "Card": 'Card.elevated {\n    Card.Header { Heading("Pro").h3 }\n    Card.Body { Text("Everything in Free, and more.") }\n    Card.Footer { Button("Choose Pro").primary }\n}',
    "Table": 'Table(caption: "Deploys") {\n    Table.Head { Table.Row { Table.Cell("Region")  Table.Cell("Status") } }\n    Table.Body { Table.Row { Table.Cell("fra1")  Table.Cell("Healthy") } }\n}',
    "List": 'List {\n    List.Item { Text("Milk") }\n    List.Item { Text("Eggs") }\n}\nList.ordered { List.Item { Text("First") } }',
    "Badge": 'Badge("Beta").info\nBadge("3 new").danger.pill',
    "Tag": 'Tag("design")',
    "Avatar": 'Avatar(src: "/ada.jpg", alt: "Ada Lovelace")\nAvatar(initials: "AL").primary.lg',
    "Tooltip": 'Tooltip("Copies the link") { IconButton(icon: "copy", label: "Copy link") }',
    "Input": 'state email = ""\nInput(bind: email, label: "Email", hint: "We never share it").email.required',
    "Select": 'state plan = "free"\nSelect(bind: plan, label: "Plan") {\n    Select.Option("Free", value: "free")\n    Select.Option("Team", value: "team")\n}',
    "Checkbox": 'state agree = false\nCheckbox(bind: agree, label: "I agree to the terms")',
    "Radio": 'state size = "m"\nRadio(bind: size, value: "s", label: "Small")\nRadio(bind: size, value: "m", label: "Medium")',
    "Switch": 'state notify = true\nSwitch(bind: notify, label: "Email me about replies")',
    "Slider": 'state volume = 50\nSlider(bind: volume, min: 0, max: 100, step: 5, label: "Volume")',
    "DatePicker": 'state start: Date? = null\nDatePicker(bind: start, label: "Start date", min: "2026-01-01")',
    "FileUpload": 'FileUpload(accept: "image/*", label: "Choose a picture") { on change(e) { log(e.target.files[0].name) } }',
    "Form": 'state name = ""\nForm(bind: form) {\n    on submit { log(name) }\n    Input(bind: name, label: "Name").required\n    Button("Save", type: .submit, disabled: !form.valid).primary\n}',
    "Textarea": 'state note = ""\nTextarea(bind: note, label: "Notes", rows: 4, maxLength: 200)',
    "Alert": 'Alert("Your changes were saved.").success\nAlert("The server is not answering.").danger',
    "Toast": 'state saved = false\nif saved { Toast("Saved").success }',
    "Modal": 'state open = false\nButton("Delete") { on click { open = true } }\nModal(visible: open, title: "Delete this?") {\n    Text("This cannot be undone.")\n    Modal.Footer { Button("Cancel") { on click { open = false } } }\n}',
    "Dialog": 'state asking = false\nDialog(visible: asking, title: "Leave without saving?") { Text("Your draft will be lost.") }',
    "Spinner": 'Spinner\nSpinner.lg',
    "Progress": 'Progress(value: 40, max: 100)',
    "Skeleton": 'Skeleton(height: "20px", width: "200px")\nSkeleton(size: "48px").circle',
    "Button": 'Button("Save").primary { on click { log("saved") } }\nButton("Delete").danger.outlined.sm\nButton("Send", type: .submit).primary.full',
    "IconButton": 'IconButton(icon: "close", label: "Close")\nIconButton(icon: "edit", label: "Edit the title").primary.sm',
    "ButtonGroup": 'ButtonGroup {\n    Button("Day")\n    Button("Week")\n    Button("Month")\n}',
    "Dropdown": 'Dropdown(label: "Actions") {\n    Dropdown.Item { Text("Duplicate") }\n    Dropdown.Divider\n    Dropdown.Item { Text("Archive") }\n}',
    "Image": 'Image(src: "/team.jpg", alt: "The team at the launch", width: 1200, height: 630)\nImage(src: "/flourish.svg", alt: "")',
    "Video": 'Video(src: "/demo.mp4", captions: "/demo.en.vtt", poster: "/demo.jpg").controls',
    "Audio": 'Audio(src: "/episode-1.mp3", transcript: "/episode-1.txt").controls',
    "Icon": 'Icon("search")\nIcon("check").lg.success',
    "Carousel": 'Carousel(label: "Recent work", autoplay: true, interval: 5000) {\n    Carousel.Slide { Image(src: "/one.jpg", alt: "A bridge at dusk") }\n    Carousel.Slide { Image(src: "/two.jpg", alt: "The harbour") }\n}',
    "Text": 'Text("Hello, world")\nText("Last updated today").muted.sm\nText("Important").bold.danger',
    "Heading": 'Heading("Pricing").h1\nHeading("Frequently asked").h2',
    "Code": 'Text("Run ")\nCode("wf serve")\nCode("page Home(path: \\"/\\") { Text(\\"Hi\\") }", language: "wf").block',
    "Markdown": 'Markdown("Some **bold** text and a [link](/docs).")',
    "Unsafe": 'state body = "<p>From the CMS</p>"\nUnsafe.Html(sanitize(body))',
    "Blockquote": 'Blockquote { Text("Make it work, make it right, make it fast.") }',
    "Document": 'Document(page_size: "A4") {\n    Section { Heading("Report").h1  Paragraph("Revenue grew.") }\n}',
    "Section": 'Section {\n    Heading("Terms").h2\n    Text("Payment within 30 days.")\n}',
    "Paragraph": 'Paragraph("A block of prose, with the spacing a paragraph has.")',
    "Header": 'Header { Text("Company Inc.").muted.sm }',
    "Footer": 'Footer { Text("© Company Inc.").muted.sm }',
    "PageBreak": 'Text("End of chapter one.")\nPageBreak\nHeading("Chapter two").h2',
    "Presentation": 'Presentation {\n    TitleSlide("Q1 review", subtitle: "March 2026")\n    Slide { Heading("Highlights").h1 }\n}',
    "Slide": 'Presentation {\n    Slide {\n        Heading("Revenue").h1\n        Text("Up 18% on last quarter.")\n    }\n}',
    "TitleSlide": 'Presentation { TitleSlide("Q1 review", subtitle: "Acme, March 2026") }',
    "SectionSlide": 'Presentation { SectionSlide("Numbers").primary }',
    "TwoColumn": 'Presentation {\n    TwoColumn {\n        Container { Heading("Wins").h3 }\n        Container { Heading("Risks").h3 }\n    }\n}',
    "ImageSlide": 'Presentation { ImageSlide(src: "chart.png", caption: "Revenue by month") }',
    "Router": 'app {\n    Navbar { Navbar.Brand { Link("Acme", to: "/") } }\n    Router(transition: .fade, duration: "200ms")\n}',
}
