name = "WebFluent"
grammar = "webfluent"
path_suffixes = ["wf"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
word_characters = ["_"]
